### ISSUE TITLE
Optris Xi 400

### ISSUE THREAD

**Issue by OptrisBeginner** [evocortex/optris_drivers#31]
Hi, 
I have an issue with Xi 400 camera when running on Linux system. I am able to get serial number and calibration files, everything seems to work except streaming video. 
I can't do non of application examples, all of them come with following error>
“Error occurred in starting stream ... aborting. You may need to reconnect the camera.”
I am not able to run guvcview either, a black damaged screen shows up, instead of a green screen. 
anyone have an idea what cause this issue, and how can I fix it. Thanks
 DEBUG [IRDeviceParams.cpp:164] @ 0.000528076s :Parameters
DEBUG [IRDeviceParams.cpp:165] @ 0.000628906s :serial: 19104157
DEBUG [IRDeviceParams.cpp:166] @ 0.000716064s :videoformatindex: 0
DEBUG [IRDeviceParams.cpp:167] @ 0.000751953s :fov: 80
DEBUG [IRDeviceParams.cpp:168] @ 0.000774902s :optics_text: 
DEBUG [IRDeviceParams.cpp:169] @ 0.000804932s :formatspath: /usr/share/libirimager
DEBUG [IRDeviceParams.cpp:170] @ 0.000828857s :calipath: /usr/share/libirimager/cali
DEBUG [IRDeviceParams.cpp:171] @ 0.00085791s :temperature min: 0
DEBUG [IRDeviceParams.cpp:172] @ 0.000880859s :temperature max: 250
DEBUG [IRDeviceParams.cpp:173] @ 0.000916992s :framerate: 32
DEBUG [IRDeviceParams.cpp:174] @ 0.000968994s :bispectral: 0
DEBUG [IRDeviceParams.cpp:175] @ 0.00101685s :average: 0
DEBUG [IRDeviceParams.cpp:176] @ 0.00106104s :flag automatic: 1
DEBUG [IRDeviceParams.cpp:177] @ 0.00110889s :min interval: 15
DEBUG [IRDeviceParams.cpp:178] @ 0.00115503s :max interval: 0
DEBUG [IRDeviceParams.cpp:179] @ 0.00123999s :chip heating mode: 0
DEBUG [IRDeviceParams.cpp:180] @ 0.00128491s :chip heating fixed val: 40
DEBUG [IRDeviceParams.cpp:181] @ 0.00132007s :focus:  50
DEBUG [IRDeviceParams.cpp:182] @ 0.00135498s :enable extended temp range: 0
DEBUG [IRDeviceParams.cpp:183] @ 0.00138794s :buffer queue size: 5
DEBUG [IRDeviceParams.cpp:184] @ 0.00141895s :enable high precision: 0
INFO [IRDeviceCreate.cpp:33] @ 0.00146387s :Searching for attached device...
DEBUG [UdevHelper.cpp:93] @ 0.0897371s :Try opening video device /dev/video0 ... success
DEBUG [IRDeviceUVC.cpp:25] @ 0.0912939s :Instantiated ImagerUVC
DEBUG [IRDeviceUVC.cpp:148] @ 0.0913489s :OpenDevice
DEBUG [IRDeviceUVC.cpp:174] @ 0.0913789s :Try opening video device /dev/video0 ... success
DEBUG [IRDeviceUVC.cpp:207] @ 0.091395s :Stream size: 382 x 290
DEBUG [IRDeviceUVC.cpp:223] @ 0.0914199s :Pixelformat: 1448695129, Frequency: 27
DEBUG [IRDeviceUVC.cpp:236] @ 0.091437s :VIDIOC_QUERYCAP successful for Xi IMAGER: Xi IMAGER
DEBUG [IRDeviceUVC.cpp:78] @ 0.118896s :initMmap
DEBUG [IRDeviceUVC.cpp:110] @ 0.119096s :mmap request: 5 buffers
DEBUG [Cali.cpp:97] @ 0.119284s :Calibration directory path: /usr/share/libirimager/cali
DEBUG [Cali.cpp:98] @ 0.119315s :Calibration file name: Cali-19104157.xml
DEBUG [Cali.cpp:108] @ 0.119397s :Calibration data A: 1450 B:400 C:4095 D:1000
INFO [IRImager.cpp:272] @ 0.119526s :Init thermal imager with size: 382x290@27 Hz
DEBUG [IRImager.cpp:378] @ 0.119631s :Using HID control interface
DEBUG [IRImager.cpp:1274] @ 0.211813s :Set focusmotor position to 50 %
DEBUG [IRImager.cpp:424] @ 0.211882s :Frameconfig - width(in): 382, height(in): 290, interval: 370370, max framerate: 27, HW interval: 0.037037
DEBUG [ImageProcessing.cpp:178] @ 0.225151s :Source buffer size: 221560 Width: 382 Height: 290
DEBUG [OpSource.cpp:332] @ 0.267198s :Using formats path: /usr/share/libirimager/Formats.def
DEBUG [OpSource.cpp:561] @ 0.267397s :Format found with size: 382
DEBUG [OpSource.cpp:332] @ 0.267449s :Using formats path: /usr/share/libirimager/Formats.def
DEBUG [ImageProcessing.cpp:109] @ 0.272848s :Source buffer size: 221560 Width: 382 Height: 290
DEBUG [OpSource.cpp:332] @ 0.272916s :Using formats path: /usr/share/libirimager/Formats.def
DEBUG [OpSource.cpp:561] @ 0.273068s :Format found with size: 382
DEBUG [IRImager.cpp:812] @ 0.273818s :Caught onFrameInit with size: 382x288
DEBUG [OpCorr.cpp:440] @ 0.275825s :Read cali: /usr/share/libirimager/cali/Cali-19104157-80-0-250.dat
DEBUG [OpCorr.cpp:530] @ 0.275874s :Read calibration of camera no 19104157, # of fields: 6 , start of fields: 40
DEBUG [ImageProcessing.cpp:949] @ 0.604114s :Update flag temperature: 34.5
DEBUG [ImageProcessing.cpp:952] @ 0.6093s :Update box temperature: 34.4375
DEBUG [IRImager.cpp:522] @ 0.622933s :Chip heating disabled
DEBUG [IRDeviceUVC.cpp:305] @ 0.629945s :startStreaming
DEBUG [IRDeviceUVC.cpp:305] @ 10.6479s :startStreaming
ERROR [IRDeviceUVC.cpp:320] @ 10.6479s :Error in queuing buffer: Invalid argument index: 0
ERROR [IRDeviceUVC.cpp:320] @ 10.648s :Error in queuing buffer: Invalid argument index: 1
ERROR [IRDeviceUVC.cpp:320] @ 10.648s :Error in queuing buffer: Invalid argument index: 2
ERROR [IRDeviceUVC.cpp:320] @ 10.6481s :Error in queuing buffer: Invalid argument index: 3
ERROR [IRDeviceUVC.cpp:320] @ 10.6481s :Error in queuing buffer: Invalid argument index: 4
DEBUG [IRDeviceUVC.cpp:428] @ 20.858s :Select error
DEBUG [OpMetadata.cpp:86] @ 20.8635s :Possible data corruption: 0 0 0 86.926
DEBUG [IRDeviceUVC.cpp:428] @ 21.0682s :Select error
DEBUG [IRDeviceUVC.cpp:428] @ 21.2693s :Select error

**Comment by worldpotato** [comment]
hi @OptrisBeginner did you solved the problem?
I ask because I want to use the optrisPI400 in my bachelor project together with ros melodic.

Cheers

**Comment by stefanmay** [comment]
Did you try the "nodrop" option?
$ sudo rmmod uvcvideo
$ sudo modprobe uvcvideo nodrop=1
Then, try guvcview. Options can be made permanent, if this solves the problem (see documentation)

**Comment by OptrisBeginner** [comment]
Hi,
I have fixed the issue and the IR Camera works fine and I am now working with some tolerance issues.
Thank you for your comment. 
Regards

**Comment by LionelMommeja** [comment]
Hello, the nodrop option fixed the same problem for me. Tx a lot. 
Now I enter into another problem with the sample serialize_raw within irimager sdk on a thermoimager camera TIM450:
 "DEBUG [IRDeviceUVC.cpp:468] @ 9.31939s :Incomplete frame transmission, bytes: 56, width: 382, height: 290".

**Comment by brianFruit** [comment]
Hi @LionelMommeja, I'm also having the same issue as you on Ubuntu 18, Melodic. Ubuntu 16 Kinetic works fine though, so it doesn't seem to be a hardware problem. Did you resolve the issue?
DEBUG [IRDeviceUVC.cpp:468] @ 0.726175s :Incomplete frame transmission, bytes: 3334, width: 382, height: 290

**Comment by LionelMommeja** [comment]
> 
> 
> Hi @LionelMommeja, I'm also having the same issue as you on Ubuntu 18, Melodic. Ubuntu 16 Kinetic works fine though, so it doesn't seem to be a hardware problem. Did you resolve the issue?
> DEBUG [IRDeviceUVC.cpp:468] @ 0.726175s :Incomplete frame transmission, bytes: 3334, width: 382, height: 290

@brianFruit unfortunately I didn't resolve the issue. I will come back to this problem in the next weeks. So I am still interested in a resolution.
